// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type Quote struct {
	ID     int32  `json:"id"`
	Author string `json:"author"`
	Quote  string `json:"quote"`
}
